version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    extra_hosts: 
      - "host.docker.internal:host-gateway"